name: Airflow DAG Workflow

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  run_airflow_dag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8  # Change this to your Python version

      - name: Install Dependencies
        run: |
          pip install apache-airflow
          pip install scikit-learn evidently pandas  # If you have any additional dependencies

      - name: Run Airflow DAG
        run: |
          airflow dags trigger --conf '{"key":"value"}' conditional_model_drift_detection_dag
