name: Run Airflow DAG

on:
  push:
    branches:
      - main

jobs:
  run_airflow_dag:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Create DAGs directory
      run: mkdir -p $GITHUB_WORKSPACE/dags/

    - name: Copy DAG file
      run: cp model_drift_dag.py $GITHUB_WORKSPACE/dags/

    - name: Install dependencies
      run: |
        pip install apache-airflow
        pip install pandas
        pip install scikit-learn
        pip install evidently
        pip install feature_engine

    - name: Set up Airflow
      run: |
        export AIRFLOW_HOME=$(pwd)
        airflow db init

    - name: Run Airflow scheduler
      run: |
        airflow scheduler 

    - name: Wait for scheduler to start
      run: sleep 10

    - name: Edit airflow.cfg
      run: |
        echo "[core]" >> $GITHUB_WORKSPACE/airflow.cfg
        echo "dags_folder = $GITHUB_WORKSPACE" >> $GITHUB_WORKSPACE/airflow.cfg

    - name: Run Airflow DAG
      run: |
        airflow dags trigger model_drift_dag -r now

    - name: Tear down Airflow
      run: |
        pkill -f "airflow scheduler"
