name: Airflow Workflow

on:
  push:
    branches:
      - main

jobs:
  run_airflow_dag:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install apache-airflow
        pip install scikit-learn evidently pandas

    - name: Initialize Airflow database
      run: airflow db init

    - name: Create DAGs directory
      run: mkdir -p $GITHUB_WORKSPACE/dags/

    - name: Copy DAG file
      run: cp model_drift_dag.py $GITHUB_WORKSPACE/dags/

    - name: Start Airflow Scheduler
      run: airflow scheduler --daemon

    - name: Trigger Airflow DAG
      run: airflow dags trigger -r conditional_model_drift_detection_dag

    - name: Wait for DAG to complete
      run: sleep 30  # Adjust the sleep duration based on your DAG runtime

    - name: Stop Airflow Scheduler
      run: airflow scheduler --stop

    - name: Display Airflow Logs
      run: cat $AIRFLOW_HOME/logs/conditional_model_drift_detection_dag/detect_model_drift_task/latest/*

