name: Run Airflow DAG

on:
  push:
    branches:
      - main

jobs:
  run_airflow_dag:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Create DAGs directory
      run: mkdir -p $GITHUB_WORKSPACE/dags/

    - name: Copy DAG file
      run: cp model_drift_dag.py $GITHUB_WORKSPACE/dags/

    - name: Install dependencies
      run: |
        pip install apache-airflow
        pip install pandas
        pip install scikit-learn
        pip install evidently
        pip install feature_engine

    - name: Set up Airflow
      run: |
        export AIRFLOW_HOME=$(pwd)
        airflow db init
        airflow users create --username admin --firstname Admin --lastname User --role Admin --email sandeepoffice10@gmail.com --password admin


    - name: Run Airflow scheduler
      run: airflow scheduler
           

    - name: Wait for scheduler to start
      run: sleep 10

    - name: Run Airflow DAG
      run: airflow dags trigger conditional_model_drift_detection_dag -r now

    - name: Tear down Airflow
      run: |
        pkill -f "airflow scheduler"
